KS-1-1-2-3-4-5
JeyziJetbalance/KotlinSprint pull request #1
Opened 2023-10-04 21:33 UTC by JeyziJetbalance

Выполнил задания по lesson_1

2023-10-05 06:31 UTC, ievetrov requested changes

2023-10-05 06:31 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_1.kt
> +    val numberOfOrder: Byte = 75
первое задание ок, по нему могу поставить аппрув)

но давай в этом мр оставим только эту задачу, так как каждая задача должна быть в отдельной ветке и на каждую должен быть отдельный мр) иначе это нарушает гитфлоу. при коммите их достаточно не отмечать галкой и не добавлять в стейдж

2023-10-05 07:07 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_1/lesson_1_task_1.kt
> +    val numberOfOrder: Byte = 75
Хорошо понял

2023-10-05 08:59 UTC, ievetrov requested changes

2023-10-05 08:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_2.kt
> +//    val listEmployees: Short = 2000
эту переменную мы инициализируем и оставляем как есть

2023-10-05 08:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_2.kt
> +    val listEmployees: Short = 1999
затем выполнить ее вывод
затем нужно не создать новую, а именно перезаписать текущую
и перед новым выводом в консоль, предыдущий закомментировать

2023-10-05 08:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour = "09:"
нужно сразу привыкать в переменных хранить только голые значения. тк предполагаем, что они приходят из базы данных. поэтому оставь только время, а оформление выполни в выводе

2023-10-05 08:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_4.kt
> +fun main() {
тут все ок

2023-10-05 08:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    val second = "00"
задача "со звездочкой")
нужно все вычисления произвести в коде. с помощью арифметических операций и правильно вывести согласно формату.
в коде сначала проинициализируй исходную переменную `val totalSeconds = 6480` и с ней уже работай

2023-10-06 06:49 UTC, ievetrov requested changes

2023-10-06 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour = 9
Задача обращает внимание на ноль в начале числа. Давай эти значения оформим строками в правильном формате. Это тоже нормальная практика, когда сервер присылает время/дату в текстовом формате. Так что тут корректно будет выводить именно строковый тип

2023-10-06 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    println(" 0" + hour + ":" + minute)
тогда здесь не придется ставить 0 в начале строки. плюс правильнее выводить переменные в таком виде:     `println("$hour:$minute")`

2023-10-06 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    print("" + hour + ":" + minute)
и здесь тоже

2023-10-06 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("0" + hour + ":" + minute + ":" + "0" + second)
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение) Для корректного вывода попробуй посмотреть в сторону String.format()

2023-10-08 07:21 UTC, ievetrov approved these changes

2023-10-13 12:49 UTC, ievetrov requested changes

2023-10-13 12:49 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +//    var second: Int = 6480
все ок, только закомментированные куски кода не принято оставлять в итоговом варианте)

2023-10-13 13:25 UTC, ievetrov approved these changes

2023-10-14 13:05 UTC, merged