KS-6-4
JeyziJetbalance/KotlinSprint pull request #25
Opened 2023-10-22 17:47 UTC by JeyziJetbalance

2023-10-23 13:46 UTC, ievetrov requested changes

2023-10-23 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +        var userNumber = readln().toInt()
по умолчанию все переменные, которые мы не изменяем в коде принято делать `val`

2023-10-23 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +    while (counter >= 0) {
здесь нужно сделать просто `counter > 0`, иначе пользователю дается 6 попыток вместо 5

2023-10-23 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +        if (counter == 0) println("Было загадано число $randomNumber.")
этот принт можно вынести за цикл

2023-10-23 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +        } else println("Неверно, оставшееся число попыток ${--counter}.")
если у `if` используются фигурные скобки, то и у `else` принято их ставить)

2023-10-24 20:00 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +    while (counter >= 0) {
Нет, дается 5 попыток, все правильно

2023-10-25 05:35 UTC, ievetrov approved these changes

2023-10-27 16:05 UTC, merged