KS-6-5
JeyziJetbalance/KotlinSprint pull request #26
Opened 2023-10-22 18:26 UTC by JeyziJetbalance

2023-10-23 13:54 UTC, ievetrov requested changes

2023-10-23 13:54 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +    while (counter == 0) {
давай разделим эти 2 флоу, первый цикл будет реализовывать авторизацию (также с 3 попытками и в случае трех неверных попыток просто делаем `return` из программы), для второго цикла также, только с решением математических примеров

3 попытки стоит вынести в константу)

2023-10-23 13:54 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +                println("Отказано в доступе.")
этот принт можно вынести за цикл, так как в случае успеха мы делаем `return` из программы

2023-10-24 20:25 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +                println("Отказано в доступе.")
Если его вынести вроде он не сработает, тк как раз мы делаем return

2023-10-25 05:37 UTC, ievetrov approved these changes

2023-10-27 16:05 UTC, merged