lesson_2_task_3
JeyziJetbalance/KotlinSprint pull request #4
Opened 2023-10-05 21:13 UTC by JeyziJetbalance

2023-10-06 09:51 UTC, ievetrov requested changes

2023-10-06 09:51 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    val arrivalTime_2 = ( departureTime + travelTime ) % 60
нижнее подчеркивание это уже другой стиль написания - snake case. но классические переменные всегда именуются в camel case. 

но добавлю, что индексы в названии использовать вообще не рекомендуется

2023-10-06 09:51 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    val arrivalTime_2 = ( departureTime + travelTime ) % 60
лучше назвать переменные более релевантно, чтобы они отражали то, что хранят (часы, минуты)

2023-10-06 09:51 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println( "" + arrivalTime + ":" + arrivalTime_2 )
а зачем вначале пустая строка?
в целом работает, но давай будем использовать интерполяцию (тема со строками)

2023-10-06 09:59 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println( "" + arrivalTime + ":" + arrivalTime_2 )
Без это строки ошибку выводит, не знаю как фиксить

2023-10-06 10:00 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println( "" + arrivalTime + ":" + arrivalTime_2 )
Хотя можно через знакомых доллара

2023-10-06 10:00 UTC, JeyziJetbalance commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println( "" + arrivalTime + ":" + arrivalTime_2 )
Знак*

2023-10-08 11:32 UTC, ievetrov approved these changes
отлично!

2023-10-14 13:06 UTC, merged