KS-3-1
JeyziJetbalance/KotlinSprint pull request #7
Opened 2023-10-08 20:58 UTC by JeyziJetbalance

2023-10-08 21:10 UTC, JeyziJetbalance commented
Второй коммит залил случайно, не знаю как удалить.

2023-10-09 17:07 UTC, ievetrov requested changes

2023-10-09 17:07 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +fun main() {
да, давай уберем эту задачку, чтобы не нарушался гит-флоу и контекст пулл реквеста

- надо переключиться в эту ветку (3-1)
- физически удалить файл из проекта
- сделать коммит и пуш, отметив в стейдже удаленный файл
- перепроверить пулл реквест, тут должен остаться только один рабочий файл
- сдать этот ПР снова в бот к задаче 3-1

2023-10-13 13:52 UTC, ievetrov approved these changes
ок!

2023-10-14 13:09 UTC, merged